### ISSUE TITLE
Não roda

### ISSUE THREAD

**Issue by hyoretsu** [opastorello/AliExpressPechincha#1]
Após ter que instalar 3 dependências manualmente, e ainda por cima baixar o Firefox, o programa só fica em loop durante a execução do `SeleniumAliAutomation(url)`
```
[-] Erro: Não foi possivel carregar a página de login.
[!] Alerta: Ajudado 1 vezes.
[-] Erro: Não foi possivel carregar a página de login.
[!] Alerta: Ajudado 2 vezes.
```
Já até tentei rodar como administrador, não que fosse mudar muita coisa na prática.

**Comment by opastorello** [comment]
Isso e problema da sua conectado ou do link informando.

**Comment by hyoretsu** [comment]
Até cabo Ethernet eu tô usando e o link está certo e abre https://campaign.aliexpress.com/wow/gcp/slash_it/itemdetail?itemId=1005001872101204&mid=3079730788026765&aid=3689016445026765&_currency=BRL&_lang=pt_BR&fromApp=true

**Comment by opastorello** [comment]
Utilize o link corretamente exemplo https://a.aliexpress.com/_msEGjE1
