### ISSUE TITLE
O programa fecha ao abrir.

### ISSUE THREAD

**Issue by OBerga** [opastorello/AliExpressPechincha#5]
Instalei o firefox, phyton e fiz direitinhos as instalações no cmd, tentei abrir e o programa automaticamente fechou, reiniciei o computador, o programa continua fechando após a inicialização.

**Comment by opastorello** [comment]
Executar ele pelo CMD e veja se aparece alguma mensagem de erro.

**Comment by OBerga** [comment]
Apareceu isso aqui, mas meu Phyton está instalado sim e tentei re-instalar os "requirements.txt" mas já estavam todos instalados...
![erro](https://user-images.githubusercontent.com/82184894/118385737-083a2300-b5e8-11eb-9257-7146b52bcec0.png)

**Comment by opastorello** [comment]
Você não definiu o python no PATH

https://datatofish.com/add-python-to-windows-path/
