### ISSUE TITLE
Consigo fazer um bot que compra?

### ISSUE THREAD

**Issue by guirms** [opastorello/AliExpressPechincha#7]
Olá amigo, você saberia me responder se  é possível a realização de um bot que compra produtos no AliExpress? Desde já, obrigado

**Comment by opastorello** [comment]
Olá amigo, sim é possível e tenho no meu git uma versão que usava para comprar produtos das promoções das 21h.

https://github.com/opastorello/AliExpressAutoCompra

**Comment by guirms** [comment]
Muito obrigado pela ajuda!
