### ISSUE TITLE
Atualização do bot de compra do pechicnha

### ISSUE THREAD

**Issue by allanssilva** [opastorello/AliExpressPechincha#8]
Fala irmão, ainda é possível a utilização desse bot do pechincha? Sou muito leigo no assunto, até tentei fazer algumas mudanças nesse disponibilizado, mas não deu certo, agradeço demais a prestatividade de sempre, sucesso!

**Comment by opastorello** [comment]
Olá esta versão não é mais possível ser utilizada, mas ainda é possível utilizar bots, mas este não
